"""empty message

Revision ID: 14818855662c
Revises: f8eaca381d54
Create Date: 2019-06-26 16:16:56.862310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14818855662c'
down_revision = 'f8eaca381d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_img', sa.Column('path', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user_img', 'user', ['user_id'], ['id'])
    op.drop_column('user_img', 'data')
    op.drop_column('user_img', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_img', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user_img', sa.Column('data', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'user_img', type_='foreignkey')
    op.drop_column('user_img', 'path')
    # ### end Alembic commands ###
