"""empty message

Revision ID: 6603b14e5ee5
Revises: 14818855662c
Create Date: 2019-06-26 16:39:24.310714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6603b14e5ee5'
down_revision = '14818855662c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_img', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_img', type_='foreignkey')
    # ### end Alembic commands ###
