"""empty message

Revision ID: 89748fbf6702
Revises: b2603eee112c
Create Date: 2019-06-03 02:11:06.767036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89748fbf6702'
down_revision = 'b2603eee112c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_img', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_img', type_='foreignkey')
    # ### end Alembic commands ###
