"""empty message

Revision ID: b2603eee112c
Revises: 0fe065e94c90
Create Date: 2019-06-03 01:21:45.274287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2603eee112c'
down_revision = '0fe065e94c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_img', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_img', type_='foreignkey')
    # ### end Alembic commands ###
