"""empty message

Revision ID: c35f1a99ae82
Revises: 
Create Date: 2019-06-02 19:11:12.788097

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from app.models.user import User

# revision identifiers, used by Alembic.
revision = 'c35f1a99ae82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(User.genders), nullable=True),
    sa.Column('born_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
